main: remove the DeleteOnClose widget attribute
Do not delete widgets when the main window is closed, as doing so causes
the Python-side objects to outlive their wrapped C++ counterparts.

Opening the DAG window and displaying a diff in it after closing the
main window runs into the following error which this change remedies:

  File "cola/cmds.py", line 1663, in do
    self.context.notifier.notify(Messages.DIFF_LOADING)
  File "cola/app.py", line 797, in notify
    self.message.emit(message)
  RuntimeError: wrapped C/C++ object of type Notifier has been deleted

Closes: #1592
Reported-by: Stanislaw Halik <sthalik@misaki.pl>
Signed-off-by: David Aguilar <davvid@gmail.com>